### ISSUE TITLE
TypeException on start 

### ISSUE THREAD

**Issue by matthiasg** [chjj/ttystudio#6]
Not sure windows is even supported but i get the following error when running `ttystudio output.gif`

```
TypeError: Cannot read property 'data' of undefined
    at GIFWriter.writeHead (C:\Users\mgt57_000\AppData\Roaming\npm\node_modules\ttystudio\lib\gif.js:115:13)\lib\pty_win.js:55:9)
    at GIFWriter.write (C:\Users\mgt57_000\AppData\Roaming\npm\node_modules\ttystudio\lib\gif.js:51:8)on (net.js:1191:8)
    at SGRWriter.write (C:\Users\mgt57_000\AppData\Roaming\npm\node_modules\ttystudio\lib\writer.js:53:22)
    at compile (C:\Users\mgt57_000\AppData\Roaming\npm\node_modules\ttystudio\bin\ttystudio:61:10)
    at C:\Users\mgt57_000\AppData\Roaming\npm\node_modules\ttystudio\bin\ttystudio:93:12
    at process.done (C:\Users\mgt57_000\AppData\Roaming\npm\node_modules\ttystudio\lib\record.js:92:7)
    at process.emit (events.js:117:20)
    at process.exit (node.js:711:17)
    at Object._onImmediate (C:\Users\mgt57_000\AppData\Roaming\npm\node_modules\ttystudio\node_modules\blessed\lib\widgets\screen.js:188:15)
    at processImmediate [as _immediateCallback] (timers.js:345:15)
```

**Comment by chjj** [comment]
Windows is technically supported through winpty, but I personally don't maintain the windows aspect of pty.js. Did it build okay? I recommend running the pty.js tests and see what output you get. Then post an issue here: https://github.com/chjj/pty.js

**Comment by jfinstrom** [comment]
In linux I think this is the same

```
TypeError: value is out of bounds
    at TypeError (<anonymous>)
    at checkInt (buffer.js:784:11)
    at Buffer.writeUInt8 (buffer.js:794:5)
    at GIFWriter.write8 (/usr/lib/node_modules/ttystudio/lib/gif.js:82:7)
    at GIFWriter.writeFrame (/usr/lib/node_modules/ttystudio/lib/gif.js:196:12)
    at GIFWriter.write (/usr/lib/node_modules/ttystudio/lib/gif.js:61:10)
    at SGRWriter.write (/usr/lib/node_modules/ttystudio/lib/writer.js:53:22)
    at compile (/usr/lib/node_modules/ttystudio/bin/ttystudio:61:10)
    at /usr/lib/node_modules/ttystudio/bin/ttystudio:93:12
    at Screen.done (/usr/lib/node_modules/ttystudio/lib/record.js:93:7)
```

**Comment by jfinstrom** [comment]
Also may be the same as #10

**Comment by jfinstrom** [comment]
In lib/gif.js I did a console log of "ch" before line 82 and it gets "undefined" where it craps out.

**Comment by chjj** [comment]
@jfinstrom, this is most likely a different issue. I'll keep it open until I can test on windows.

**Comment by chjj** [comment]
Ah, the joys of windows. Install VS C++ 2010 Express - BSOD on boot. I'll try again with a new image some other time.
